apiVersion: v1
kind: Service
metadata:
  name: db-fairyAnimal
spec:
  type: ClusterIP
  ports:
    - name: "db-fairyAnimal"
      port: 5432
      targetPort: 5432
  selector:
    app: db-fairyAnimal
