apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-fairyanimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-fairyanimal
  template:
    metadata:
      labels:
        app: db-fairyanimal
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: fairyanimal
            - name: POSTGRES_PASSWORD
              value: "hello"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          name: db-fairyanimal
          ports:
            - containerPort: 5432
