apiVersion: v1
kind: Service
metadata:
  name: example-fairyAnimals
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 7082
      targetPort: 7082
  selector:
    app: example-fairyAnimals