apiVersion: v1
kind: Service
metadata:
  name: example-foods
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8085
      targetPort: 8085
    - name: grpc
      port: 7085
      targetPort: 7085
  selector:
    app: example-foods