apiVersion: v1
kind: Service
metadata:
  name: example-terrains
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8084
      targetPort: 8084
    - name: grpc
      port: 7084
      targetPort: 7084
  selector:
    app: example-terrains